fail_fast: false
repos:
  -   repo: https://github.com/ambv/black
      rev: 18.9b0
      hooks:
      - id: black
        args: [--line-length=100, --safe]
        language_version: python3
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.3.0
      hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: flake8
        args: ['--max-line-length=100']
